"""Initial Migration4

Revision ID: 477eb12653bb
Revises: ad89a6ce5753
Create Date: 2019-03-02 19:46:52.718382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477eb12653bb'
down_revision = 'ad89a6ce5753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=True)
    op.create_index(op.f('ix_subscribers_username'), 'subscribers', ['username'], unique=False)
    op.drop_index('ix_subcribers_email', table_name='subcribers')
    op.drop_index('ix_subcribers_username', table_name='subcribers')
    op.drop_table('subcribers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcribers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='subcribers_pkey')
    )
    op.create_index('ix_subcribers_username', 'subcribers', ['username'], unique=False)
    op.create_index('ix_subcribers_email', 'subcribers', ['email'], unique=True)
    op.drop_index(op.f('ix_subscribers_username'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
