"""Initial Migration2

Revision ID: 8c3aeb2f969c
Revises: 99026d3b491b
Create Date: 2019-03-02 19:02:45.831011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c3aeb2f969c'
down_revision = '99026d3b491b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcribers_email'), 'subcribers', ['email'], unique=True)
    op.create_index(op.f('ix_subcribers_username'), 'subcribers', ['username'], unique=False)
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_index(op.f('ix_subcribers_username'), table_name='subcribers')
    op.drop_index(op.f('ix_subcribers_email'), table_name='subcribers')
    op.drop_table('subcribers')
    # ### end Alembic commands ###
