"""Initial Migration2

Revision ID: 99026d3b491b
Revises: bc38e948c9b7
Create Date: 2019-03-02 13:34:49.312988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99026d3b491b'
down_revision = 'bc38e948c9b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('post_id', sa.Integer(), nullable=True))
    op.drop_constraint('comments_pitch_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    op.drop_column('comments', 'pitch_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_pitch_id_fkey', 'comments', 'posts', ['pitch_id'], ['id'])
    op.drop_column('comments', 'post_id')
    # ### end Alembic commands ###
