"""Initial Migration3

Revision ID: ad89a6ce5753
Revises: 8c3aeb2f969c
Create Date: 2019-03-02 19:46:12.685339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad89a6ce5753'
down_revision = '8c3aeb2f969c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subcribers_user_id_fkey', 'subcribers', type_='foreignkey')
    op.drop_column('subcribers', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcribers', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('subcribers_user_id_fkey', 'subcribers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
